import { getNative } from '../../../utils/native'

const FALLBACK_GITIGNORE = [
  '# Visual Studio 2015 user specific files',
  '.vs/',
  '',
  '# Compiled Object files',
  '*.slo',
  '*.lo',
  '*.o',
  '*.obj',
  '',
  '# Precompiled Headers',
  '*.gch',
  '*.pch',
  '',
  '# Compiled Dynamic libraries',
  '*.so',
  '*.dylib',
  '*.dll',
  '',
  '# Fortran module files',
  '*.mod',
  '',
  '# Compiled Static libraries',
  '*.lai',
  '*.la',
  '*.a',
  '*.lib',
  '',
  '# Executables',
  '*.exe',
  '*.out',
  '*.app',
  '*.ipa',
  '',
  '# These project files can be generated by the engine',
  '*.xcodeproj',
  '*.xcworkspace',
  '*.sln',
  '*.suo',
  '*.opensdf',
  '*.sdf',
  '*.VC.db',
  '*.VC.opendb',
  '',
  '# Binary Files',
  'Binaries/*',
  'Plugins/*/Binaries/*',
  '',
  '# Builds',
  'Build/*',
  '',
  '# Whitelist PakBlacklist-<BuildConfiguration>.txt files',
  '!Build/*/Build/*/**',
  '!Build/*/PakBlacklist*.txt',
  '',
  "# Don't ignore icon files in Build",
  '!Build/**/*.ico',
  '',
  '# Built data for maps',
  '*_BuiltData.uasset',
  '',
  '# Configuration files generated by the Editor',
  'Saved/*',
  '',
  '# Compiled source files for the engine to use',
  'Intermediate/*',
  'Plugins/*/Intermediate/*',
  '',
  '# Cache files for the editor to use',
  'DerivedDataCache/*',
  '',
  '.idea',
  'Plugins/DeveloperBuilds',
  'Config/steamvr_ue_editor_app.json',
  'Config/SteamVRBindingsPlatforms/',
  'HoloLens/Config/HoloLensEngine.ini',
  '.vsconfig'
].join('\n')

const FALLBACK_GITATTRIBUTES = [
  '# UE file types',
  '*.uasset filter=lfs diff=lfs merge=lfs -text',
  '*.umap filter=lfs diff=lfs merge=lfs -text',
  '',
  '# Raw Content types',
  '*.fbx filter=lfs diff=lfs merge=lfs -text',
  '*.3ds filter=lfs diff=lfs merge=lfs -text',
  '*.psd filter=lfs diff=lfs merge=lfs -text',
  '*.png filter=lfs diff=lfs merge=lfs -text',
  '*.mp3 filter=lfs diff=lfs merge=lfs -text',
  '*.wav filter=lfs diff=lfs merge=lfs -text',
  '*.xcf filter=lfs diff=lfs merge=lfs -text',
  '*.jpg filter=lfs diff=lfs merge=lfs -text',
  '*.uexp filter=lfs diff=lfs merge=lfs -text',
  '*.bank filter=lfs diff=lfs merge=lfs -text',
  '*.tmp filter=lfs diff=lfs merge=lfs -text',
  '*.vox filter=lfs diff=lfs merge=lfs -text',
  '',
  '# Libraries and executables',
  '*.a filter=lfs diff=lfs merge=lfs -text',
  '*.lib filter=lfs diff=lfs merge=lfs -text',
  '*.exe filter=lfs diff=lfs merge=lfs -text',
  '*.zip filter=lfs diff=lfs merge=lfs -text'
].join('\n')

export function getUeGitignore(): string {
  const native = getNative()
  if (native?.getUeGitignoreTemplate) {
    try {
      return native.getUeGitignoreTemplate()
    } catch {
      /* fallback */
    }
  }
  return FALLBACK_GITIGNORE
}

export function getUeGitattributes(): string {
  const native = getNative()
  if (native?.getUeGitattributesTemplate) {
    try {
      return native.getUeGitattributesTemplate()
    } catch {
      /* fallback */
    }
  }
  return FALLBACK_GITATTRIBUTES
}

export const UE_GITIGNORE = FALLBACK_GITIGNORE
export const UE_GITATTRIBUTES = FALLBACK_GITATTRIBUTES
