// Copyright (c) 2026 NeelFrostrain. All rights reserved.
// Proprietary and confidential. Unauthorized copying, modification,
// distribution, or use of this source code is strictly prohibited.
// See LICENSE in the project root for full license terms.
import path from 'path'
import fs from 'fs'
import { execFile } from 'child_process'
import { promisify } from 'util'

const execFileAsync = promisify(execFile)

async function runGitAsync(projectPath: string, args: string[]): Promise<Buffer> {
  const { stdout } = await execFileAsync('git', args, { cwd: projectPath, encoding: 'buffer' })
  return stdout
}

function assertValidBranchName(branch: string): void {
  if (branch.startsWith('-')) throw new Error('Invalid branch name')
  // Validate without spawning a process — covers the main git check-ref-format rules
  if (/[\x00-\x1f\x7f ~^:?*[\\\]]/.test(branch) || branch.includes('..') || branch.endsWith('.lock')) {
    throw new Error('Invalid branch name')
  }
}

const UE_GITIGNORE = [
  '# Visual Studio 2015 user specific files',
  '.vs/',
  '',
  '# Compiled Object files',
  '*.slo',
  '*.lo',
  '*.o',
  '*.obj',
  '',
  '# Precompiled Headers',
  '*.gch',
  '*.pch',
  '',
  '# Compiled Dynamic libraries',
  '*.so',
  '*.dylib',
  '*.dll',
  '',
  '# Fortran module files',
  '*.mod',
  '',
  '# Compiled Static libraries',
  '*.lai',
  '*.la',
  '*.a',
  '*.lib',
  '',
  '# Executables',
  '*.exe',
  '*.out',
  '*.app',
  '*.ipa',
  '',
  '# These project files can be generated by the engine',
  '*.xcodeproj',
  '*.xcworkspace',
  '*.sln',
  '*.suo',
  '*.opensdf',
  '*.sdf',
  '*.VC.db',
  '*.VC.opendb',
  '',
  '# Binary Files',
  'Binaries/*',
  'Plugins/*/Binaries/*',
  '',
  '# Builds',
  'Build/*',
  '',
  '# Whitelist PakBlacklist-<BuildConfiguration>.txt files',
  '!Build/*/Build/*/**',
  '!Build/*/PakBlacklist*.txt',
  '',
  "# Don't ignore icon files in Build",
  '!Build/**/*.ico',
  '',
  '# Built data for maps',
  '*_BuiltData.uasset',
  '',
  '# Configuration files generated by the Editor',
  'Saved/*',
  '',
  '# Compiled source files for the engine to use',
  'Intermediate/*',
  'Plugins/*/Intermediate/*',
  '',
  '# Cache files for the editor to use',
  'DerivedDataCache/*',
  '',
  '.idea',
  'Plugins/DeveloperBuilds',
  'Config/steamvr_ue_editor_app.json',
  'Config/SteamVRBindingsPlatforms/',
  'HoloLens/Config/HoloLensEngine.ini',
  '.vsconfig'
].join('\n')

const UE_GITATTRIBUTES = [
  '# UE file types',
  '*.uasset filter=lfs diff=lfs merge=lfs -text',
  '*.umap filter=lfs diff=lfs merge=lfs -text',
  '',
  '# Raw Content types',
  '*.fbx filter=lfs diff=lfs merge=lfs -text',
  '*.3ds filter=lfs diff=lfs merge=lfs -text',
  '*.psd filter=lfs diff=lfs merge=lfs -text',
  '*.png filter=lfs diff=lfs merge=lfs -text',
  '*.mp3 filter=lfs diff=lfs merge=lfs -text',
  '*.wav filter=lfs diff=lfs merge=lfs -text',
  '*.xcf filter=lfs diff=lfs merge=lfs -text',
  '*.jpg filter=lfs diff=lfs merge=lfs -text',
  '*.uexp filter=lfs diff=lfs merge=lfs -text',
  '*.bank filter=lfs diff=lfs merge=lfs -text',
  '*.tmp filter=lfs diff=lfs merge=lfs -text',
  '*.vox filter=lfs diff=lfs merge=lfs -text',
  '',
  '# Libraries and executables',
  '*.a filter=lfs diff=lfs merge=lfs -text',
  '*.lib filter=lfs diff=lfs merge=lfs -text',
  '*.exe filter=lfs diff=lfs merge=lfs -text',
  '*.zip filter=lfs diff=lfs merge=lfs -text'
].join('\n')

export function handleProjectGitStatus(projectPath: string): {
  initialized: boolean
  branch: string
  hasUncommitted: boolean
  ahead: number
  behind: number
  remoteUrl: string
} {
  const gitDir = path.join(projectPath, '.git')
  if (!fs.existsSync(gitDir))
    return {
      initialized: false,
      branch: '',
      hasUncommitted: false,
      ahead: 0,
      behind: 0,
      remoteUrl: ''
    }
  let branch = 'unknown'
  try {
    branch = fs
      .readFileSync(path.join(gitDir, 'HEAD'), 'utf8')
      .trim()
      .replace('ref: refs/heads/', '')
  } catch {
    /* ignore */
  }
  let remoteUrl = ''
  try {
    const m = fs.readFileSync(path.join(gitDir, 'config'), 'utf8').match(/url\s*=\s*(.+)/)
    if (m) remoteUrl = m[1].trim()
  } catch {
    /* ignore */
  }
  return { initialized: true, branch, hasUncommitted: false, ahead: 0, behind: 0, remoteUrl }
}

export async function handleProjectGitInit(
  projectPath: string
): Promise<{ success: boolean; lfsAvailable: boolean; error?: string }> {
  try {
    await runGitAsync(projectPath, ['init'])
    if (!fs.existsSync(path.join(projectPath, '.gitignore')))
      fs.writeFileSync(path.join(projectPath, '.gitignore'), UE_GITIGNORE, 'utf8')
    if (!fs.existsSync(path.join(projectPath, '.gitattributes')))
      fs.writeFileSync(path.join(projectPath, '.gitattributes'), UE_GITATTRIBUTES, 'utf8')
    let lfsAvailable = false
    try {
      await runGitAsync(projectPath, ['lfs', 'install'])
      lfsAvailable = true
    } catch {
      /* lfs not installed */
    }
    return { success: true, lfsAvailable }
  } catch (err) {
    return {
      success: false,
      lfsAvailable: false,
      error: err instanceof Error ? err.message : 'Unknown error'
    }
  }
}

export function handleProjectGitFileStatus(projectPath: string): {
  hasGitignore: boolean
  hasGitattributes: boolean
} {
  return {
    hasGitignore: fs.existsSync(path.join(projectPath, '.gitignore')),
    hasGitattributes: fs.existsSync(path.join(projectPath, '.gitattributes'))
  }
}

export async function handleProjectGitReinit(
  projectPath: string
): Promise<{ success: boolean; error?: string }> {
  try {
    await runGitAsync(projectPath, ['init'])
    return { success: true }
  } catch (err) {
    return { success: false, error: err instanceof Error ? err.message : 'Unknown error' }
  }
}

export function handleProjectGitWriteGitignore(projectPath: string): {
  success: boolean
  existed: boolean
  error?: string
} {
  const gitignore = path.join(projectPath, '.gitignore')
  const existed = fs.existsSync(gitignore)
  try {
    fs.writeFileSync(gitignore, UE_GITIGNORE, 'utf8')
    return { success: true, existed }
  } catch (err) {
    return { success: false, existed, error: err instanceof Error ? err.message : 'Unknown error' }
  }
}

export async function handleProjectGitInitLfs(
  projectPath: string
): Promise<{ success: boolean; error?: string }> {
  try {
    await runGitAsync(projectPath, ['lfs', 'install'])
    fs.writeFileSync(path.join(projectPath, '.gitattributes'), UE_GITATTRIBUTES, 'utf8')
    return { success: true }
  } catch (err) {
    return {
      success: false,
      error:
        err instanceof Error ? err.message : 'Git LFS not installed. Install it from git-lfs.com'
    }
  }
}

export async function handleProjectGitHasChanges(projectPath: string): Promise<{
  hasChanges: boolean
  summary: string
  fileList: Array<{ status: string; file: string }>
  error?: string
}> {
  try {
    const stdout = await runGitAsync(projectPath, ['status', '--porcelain'])
    const status = stdout.toString().trim()
    const lines = status ? status.split('\n').filter(Boolean) : []
    const fileList = lines.map((line) => ({
      status: line.slice(0, 2).trim() || '?',
      file: line.slice(3).trim()
    }))
    return {
      hasChanges: lines.length > 0,
      summary:
        lines.length > 0
          ? `${lines.length} file${lines.length !== 1 ? 's' : ''} changed`
          : 'No changes',
      fileList
    }
  } catch (err) {
    return {
      hasChanges: false,
      summary: '',
      fileList: [],
      error: err instanceof Error ? err.message : 'Unknown error'
    }
  }
}

export async function handleProjectGitCommit(
  projectPath: string,
  message: string
): Promise<{ success: boolean; error?: string }> {
  try {
    await runGitAsync(projectPath, ['add', '-A'])
    await runGitAsync(projectPath, ['commit', '-m', message])
    return { success: true }
  } catch (err) {
    const msg = err instanceof Error ? err.message : 'Unknown error'
    if (msg.includes('nothing to commit')) return { success: true }
    return { success: false, error: msg }
  }
}

export async function handleProjectGitBranches(
  projectPath: string
): Promise<{ branches: string[]; current: string; error?: string }> {
  try {
    const stdout = await runGitAsync(projectPath, ['branch'])
    const branches: string[] = []
    let current = ''
    for (const line of stdout.toString().split('\n')) {
      const trimmed = line.trim()
      if (!trimmed) continue
      if (trimmed.startsWith('* ')) {
        current = trimmed.slice(2)
        branches.push(current)
      } else branches.push(trimmed)
    }
    return { branches, current }
  } catch (err) {
    return {
      branches: [],
      current: '',
      error: err instanceof Error ? err.message : 'Unknown error'
    }
  }
}

export async function handleProjectGitSwitchBranch(
  projectPath: string,
  branch: string,
  create: boolean,
  strategy: 'normal' | 'stash' | 'force' = 'normal'
): Promise<{ success: boolean; error?: string; hasUncommitted?: boolean }> {
  try {
    assertValidBranchName(branch)
    if (create) {
      await runGitAsync(projectPath, ['checkout', '-b', branch])
      return { success: true }
    }
    if (strategy === 'stash') {
      await runGitAsync(projectPath, ['stash'])
      try {
        await runGitAsync(projectPath, ['checkout', branch])
        await runGitAsync(projectPath, ['stash', 'pop'])
      } catch (switchErr) {
        try { await runGitAsync(projectPath, ['stash', 'pop']) } catch { /* ignore */ }
        throw switchErr
      }
      return { success: true }
    }
    if (strategy === 'force') {
      await runGitAsync(projectPath, ['checkout', '--', '.'])
      await runGitAsync(projectPath, ['checkout', branch])
      return { success: true }
    }
    try {
      await runGitAsync(projectPath, ['checkout', branch])
      return { success: true }
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err)
      if (msg.includes('overwritten by checkout') || msg.includes('local changes'))
        return {
          success: false,
          hasUncommitted: true,
          error: 'You have uncommitted changes that would be overwritten.'
        }
      throw err
    }
  } catch (err) {
    return { success: false, error: err instanceof Error ? err.message : 'Unknown error' }
  }
}
